import pytest
import asyncio
import sys
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


class TestEditorAgent:
    def test_editor_agent_type(self):
        from agents.editor import EditorAgent
        agent = EditorAgent()
        assert agent.agent_type == "editor"

    @pytest.mark.asyncio
    async def test_editor_empty_scenes(self, monkeypatch):
        async def mock_llm(*args, **kwargs):
            return json.dumps({
                "title_card": {"text": "Test", "subtitle": "", "duration_s": 3.0},
                "scenes": [],
                "credits": {"text": "Test credits", "duration_s": 4.0},
                "total_duration_s": 7.0,
            })

        monkeypatch.setattr("agents.editor.call_llm", mock_llm)
        from agents.editor import EditorAgent
        from schemas import WorkOrder

        agent = EditorAgent()
        wo = WorkOrder(
            agent_type="editor",
            input_data={
                "title": "Test Film",
                "culture": "viking",
                "timeline": "high_medieval",
                "theme": "ambition",
                "scenes": [],
                "clip_data": [],
                "target_duration_s": 90,
            },
            story_hash="test",
            priority=1,
        )
        result = await agent.execute(wo)
        assert result.success is True
        timeline = result.output_data.get("assembly_timeline", {})
        assert "title_card" in timeline
        assert "credits" in timeline

    @pytest.mark.asyncio
    async def test_editor_with_scenes(self, monkeypatch):
        async def mock_llm(*args, **kwargs):
            return json.dumps({
                "title_card": {"text": "The Star Forge", "subtitle": "A Viking Story", "duration_s": 3.0},
                "scenes": [
                    {"index": 0, "scene_id": "scene_1", "clip_url": "", "duration_s": 10.0,
                     "transition_in": "fade_from_black", "transition_out": "crossfade",
                     "narration_start_offset_s": 1.5, "narration_text": "The river held its secret..."},
                ],
                "credits": {"text": "Generated by Chronicles", "duration_s": 4.0},
                "total_duration_s": 67.0,
            })

        monkeypatch.setattr("agents.editor.call_llm", mock_llm)
        from agents.editor import EditorAgent
        from schemas import WorkOrder

        agent = EditorAgent()
        wo = WorkOrder(
            agent_type="editor",
            input_data={
                "title": "The Star Forge",
                "culture": "viking",
                "timeline": "high_medieval",
                "theme": "ambition",
                "scenes": [{"id": "scene_1", "summary": "Bjorn at river", "location": "Frozen river", "characters": ["Bjorn"], "emotional_beat": "wonder"}],
                "clip_data": [{"scene_id": "scene_1", "source": "ken_burns", "prompt": "test"}],
                "target_duration_s": 90,
            },
            story_hash="test",
            priority=1,
        )
        result = await agent.execute(wo)
        assert result.success is True
        timeline = result.output_data["assembly_timeline"]
        assert timeline["title_card"]["text"] == "The Star Forge"


class TestSoundDesigner:
    def test_sound_designer_agent_type(self):
        from agents.sound_designer import SoundDesignerAgent
        agent = SoundDesignerAgent()
        assert agent.agent_type == "sound_designer"

    @pytest.mark.asyncio
    async def test_sound_designer_creates_timeline(self, monkeypatch):
        async def mock_llm(*args, **kwargs):
            return json.dumps({
                "s1": "Ambient forge sounds. Bjorn (gravelly): 'The iron speaks.' Hammer strikes on anvil. Fire crackling.",
            })

        monkeypatch.setattr("agents.sound_designer.call_llm", mock_llm)
        from agents.sound_designer import SoundDesignerAgent
        from schemas import WorkOrder

        agent = SoundDesignerAgent()
        wo = WorkOrder(
            agent_type="sound_designer",
            input_data={
                "narration_path": "/tmp/test.mp3",
                "culture": "viking",
                "timeline": "medieval",
                "scenes": [{"id": "s1", "summary": "test", "location": "forge", "emotional_beat": "wonder"}],
                "characters": [],
            },
            story_hash="test",
            priority=2,
        )
        result = await agent.execute(wo)
        assert result.success is True
        audio_prompts = result.output_data.get("audio_prompts", {})
        assert "s1" in audio_prompts


class TestColorist:
    def test_colorist_agent_type(self):
        from agents.colorist import ColoristAgent
        agent = ColoristAgent()
        assert agent.agent_type == "colorist"

    @pytest.mark.asyncio
    async def test_colorist_creates_grading_spec(self, monkeypatch):
        async def mock_llm(*args, **kwargs):
            return json.dumps({
                "base_grade": {"brightness": 0.0, "contrast": 1.05, "saturation": 0.95, "temperature_offset": 500, "vignette": 0.0},
                "scene_adjustments": [],
            })

        monkeypatch.setattr("agents.colorist.call_llm", mock_llm)
        from agents.colorist import ColoristAgent
        from schemas import WorkOrder

        agent = ColoristAgent()
        wo = WorkOrder(
            agent_type="colorist",
            input_data={
                "color_palette": "#D4451A, #2C1810, #000000",
                "lighting_style": "Warm forge fire",
                "emotional_arc": "wonder→obsession→redemption",
                "scene_count": 6,
            },
            story_hash="test",
            priority=2,
        )
        result = await agent.execute(wo)
        assert result.success is True
        grading = result.output_data.get("grading_spec", {})
        assert "base_grade" in grading


class TestFFmpegAssembler:
    def test_assembler_creates_minimal_mp4(self):
        from post.assembler import FFmpegAssembler
        import tempfile

        assembler = FFmpegAssembler(output_dir=Path(tempfile.mkdtemp()))
        result = assembler.assemble(
            story_hash="test_assembler",
            assembly_timeline=None,
            clip_data=None,
        )
        # FFmpeg may not be available on all systems
        if result:
            assert result.exists()
            assert result.suffix == ".mp4"
            result.unlink()

    def test_assembler_output_dir_created(self):
        from post.assembler import FFmpegAssembler
        import tempfile

        d = Path(tempfile.mkdtemp())
        assembler = FFmpegAssembler(output_dir=d / "films")
        assert assembler.output_dir.exists()

    def test_assembler_handles_empty_clips(self):
        from post.assembler import FFmpegAssembler
        import tempfile

        d = Path(tempfile.mkdtemp())
        assembler = FFmpegAssembler(output_dir=d)
        result = assembler._create_minimal_mp4("test_empty", {"title_card": {"text": "Test"}})
        if result:
            assert result.exists()
            result.unlink()
