"""
FFmpeg Assembler — the factory that produces the final MP4 film.

Takes output from Editor, SoundDesigner, Colorist agents and runs FFmpeg to:
1. Concatenate clips with transitions
2. Overlay audio (narration + optional music/SFX)
3. Apply color grading
4. Add title card + credits
5. Encode to MP4 (H.264 1080p, AAC audio)
"""

import os
import subprocess
import tempfile
from pathlib import Path
from typing import Optional, List, Dict, Any

from logger_config import setup_logger

logger = setup_logger("FFmpegAssembler")

OUTPUT_DIR = Path(__file__).parent.parent / "generated"
FFMPEG = "ffmpeg"


class FFmpegAssembler:

    def __init__(self, output_dir: Path = OUTPUT_DIR):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def assemble(
        self,
        story_hash: str,
        assembly_timeline: Optional[Dict[str, Any]] = None,
        audio_timeline: Optional[Dict[str, Any]] = None,
        grading_spec: Optional[Dict[str, Any]] = None,
        clip_data: Optional[List[Dict[str, Any]]] = None,
    ) -> Optional[Path]:
        output_path = self.output_dir / f"chronicles_{story_hash}.mp4"

        try:
            if clip_data and assembly_timeline:
                output_path = self._assemble_from_clips(
                    story_hash, assembly_timeline, audio_timeline,
                    grading_spec, clip_data,
                )
            else:
                output_path = self._create_minimal_mp4(story_hash, assembly_timeline)

            if output_path and output_path.exists():
                size_mb = output_path.stat().st_size / (1024 * 1024)
                logger.info(f"Film assembled: {output_path} ({size_mb:.1f} MB)")
                return output_path

        except FileNotFoundError:
            logger.warning("FFmpeg not found. Installing FFmpeg on the system is required.")
        except subprocess.TimeoutExpired:
            logger.warning("FFmpeg assembly timed out (300s limit).")
        except Exception as e:
            logger.warning(f"Assembly failed (graceful): {e}")

        return None

    def _assemble_from_clips(
        self, story_hash: str, timeline: Dict, audio_timeline: Optional[Dict],
        grading: Optional[Dict], clip_data: List[Dict],
    ) -> Optional[Path]:
        concat_path = self.output_dir / f"concat_{story_hash}.txt"
        output_path = self.output_dir / f"chronicles_{story_hash}.mp4"

        with open(concat_path, "w") as f:
            for clip in clip_data:
                url = clip.get("clip_url") or clip.get("url") or ""
                if url:
                    f.write(f"file '{url}'\n")

        concat_size = concat_path.stat().st_size
        if concat_size == 0:
            logger.warning("No clip URLs available for assembly")
            concat_path.unlink()
            return self._create_minimal_mp4(story_hash, timeline)

        cmd = [
            FFMPEG, "-y",
            "-f", "concat", "-safe", "0", "-i", str(concat_path),
        ]

        title = timeline.get("title_card", {}).get("text", "Chronicles Film") if timeline else "Chronicles Film"
        subtitle = timeline.get("title_card", {}).get("subtitle", "") if timeline else ""

        filter_parts = []
        filter_parts.append(
            f"drawtext=text='{title}':fontsize=36:fontcolor=white:"
            f"x=(w-text_w)/2:y=(h-text_h)/2-20:"
            f"enable='between(t,0,3)':box=1:boxcolor=black@0.6:boxborderw=20"
        )
        if subtitle:
            filter_parts.append(
                f"drawtext=text='{subtitle}':fontsize=18:fontcolor=white@0.8:"
                f"x=(w-text_w)/2:y=(h-text_h)/2+20:"
                f"enable='between(t,0,3)'"
            )

        credits_text = (timeline or {}).get("credits", {}).get("text", "Generated by Chronicles Production")
        total_dur = (timeline or {}).get("total_duration_s", 60)
        credits_start = max(0, total_dur - 5)
        filter_parts.append(
            f"drawtext=text='{credits_text}':fontsize=14:fontcolor=white@0.7:"
            f"x=(w-text_w)/2:y=h-th-30:"
            f"enable='between(t,{credits_start},{total_dur})':"
            f"box=1:boxcolor=black@0.3:boxborderw=10"
        )

        if grading and grading.get("base_grade"):
            g = grading["base_grade"]
            contrast = g.get("contrast", 1.0)
            brightness = g.get("brightness", 0.0)
            saturation = g.get("saturation", 1.0)
            filter_parts.append(
                f"eq=brightness={brightness}:contrast={contrast}:saturation={saturation}"
            )

        if filter_parts:
            cmd.extend(["-vf", ",".join(filter_parts)])

        narration_path = None
        if audio_timeline and audio_timeline.get("narration", {}).get("audio_path"):
            narration_path = audio_timeline["narration"]["audio_path"]
            if Path(narration_path).exists():
                cmd.extend([
                    "-i", narration_path,
                    "-c:v", "libx264", "-preset", "medium", "-crf", "23",
                    "-c:a", "aac", "-b:a", "128k",
                    "-shortest",
                ])
            else:
                cmd.extend([
                    "-c:v", "libx264", "-preset", "medium", "-crf", "23",
                    "-an",
                ])
        else:
            cmd.extend([
                "-c:v", "libx264", "-preset", "medium", "-crf", "23",
                "-an",
            ])

        cmd.append(str(output_path))

        logger.info(f"Running FFmpeg: {' '.join(str(c) for c in cmd)}")
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)

        concat_path.unlink(missing_ok=True)

        if proc.returncode != 0:
            logger.warning(f"FFmpeg failed (rc={proc.returncode}): {proc.stderr[-300:]}")
            return None

        return output_path

    def _create_minimal_mp4(self, story_hash: str, timeline: Optional[Dict] = None) -> Optional[Path]:
        output_path = self.output_dir / f"chronicles_{story_hash}.mp4"
        title = "Chronicles Film"
        if timeline and timeline.get("title_card"):
            title = timeline["title_card"].get("text", title)

        cmd = [
            FFMPEG, "-y",
            "-f", "lavfi", "-i", "color=c=black:s=1280x720:d=10",
            "-vf",
            f"drawtext=text='{title}':fontsize=36:fontcolor=white:"
            f"x=(w-text_w)/2:y=(h-text_h)/2:"
            f"box=1:boxcolor=black@0.5:boxborderw=20,"
            f"drawtext=text='Video clips pending GPU setup':fontsize=16:fontcolor=white@0.6:"
            f"x=(w-text_w)/2:y=(h-text_h)/2+40",
            "-c:v", "libx264", "-preset", "fast", "-crf", "23",
            "-an",
            str(output_path),
        ]

        logger.info("Creating placeholder MP4 (no GPU clips available)")
        subprocess.run(cmd, capture_output=True, timeout=30)

        if output_path.exists():
            return output_path
        return None
