from typing import List, Dict, Any

from agents.base_agent import BaseAgent
from schemas import WorkOrder, WorkResult
from prompts.editor_prompt import EDITOR_PROMPT
from utils.llm_client import call_llm
from config import CONFIG
from logger_config import setup_logger

logger = setup_logger("EditorAgent")


class EditorAgent(BaseAgent):
    agent_type = "editor"

    async def _execute_internal(self, work_order: WorkOrder) -> WorkResult:
        data = work_order.input_data
        title = data.get("title", "Chronicles Film")
        culture = data.get("culture", "")
        timeline = data.get("timeline", "")
        theme = data.get("theme", "")
        scenes = data.get("scenes", [])
        clip_data = data.get("clip_data", [])
        target_duration = data.get("target_duration_s", CONFIG.TARGET_FILM_DURATION_S)

        scenes_text = ""
        for s in scenes[:12]:
            scenes_text += (
                f"Scene {s.get('id', '?')}: {s.get('summary', '')} "
                f"[{s.get('location', '')}] "
                f"characters: {s.get('characters', [])} "
                f"emotional: {s.get('emotional_beat', '')}\n"
            )

        clip_text = ""
        for c in clip_data[:12]:
            clip_text += f"Clip {c.get('scene_id', '?')}: {c.get('source', '')} {c.get('prompt', '')[:100]}\n"

        prompt = EDITOR_PROMPT.format(
            title=title,
            culture=culture,
            timeline=timeline,
            theme=theme,
            scene_count=len(scenes),
            target_duration_s=target_duration,
            scenes=scenes_text or "No scenes provided",
            clip_data=clip_text or "No clip data",
            culture_display=culture.replace("_", " ").title() if culture else "Unknown",
            theme_display=theme.replace("_", " ").title() if theme else "Unknown",
            agent_count="35",
        )

        llm_result = await call_llm(
            system=EDITOR_PROMPT.split("## INPUT")[0],
            user=prompt,
            temperature=0.4,
            max_tokens=1500,
            task="default",
        )

        self.tokens_used = 0

        import json as _json
        timeline = {}
        try:
            if isinstance(llm_result, str):
                text = llm_result.strip()
                if text.startswith("```"):
                    text = text.split("```")[1]
                    if text.startswith("json"):
                        text = text[4:]
                timeline = _json.loads(text)
        except (_json.JSONDecodeError, AttributeError):
            timeline = {
                "title_card": {"text": title, "subtitle": "", "duration_s": 3.0},
                "scenes": [
                    {"index": i, "scene_id": s.get("id", f"s{i}"),
                     "clip_url": "", "duration_s": CONFIG.CLIP_DURATION_S,
                     "transition_in": "fade_from_black", "transition_out": "crossfade",
                     "narration_start_offset_s": 1.5, "narration_text": ""}
                    for i, s in enumerate(scenes[:CONFIG.VIDEO_CLIP_COUNT])
                ],
                "credits": {"text": "Generated by Chronicles Production", "duration_s": 4.0},
            }

        total_duration = timeline.get("total_duration_s", 90)
        logger.info(f"[{self.agent_type}] Assembly timeline: {len(timeline.get('scenes', []))} scenes, {total_duration}s")

        return WorkResult(
            success=True,
            output_data={
                "assembly_timeline": timeline,
            },
            wall_time_ms=self.wall_time_ms,
            tokens_used=self.tokens_used,
        )
